logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
       cache: DEBUG

keystone:
  endpoint: http://127.0.0.1:5000/v3
  domain: default
  project: library

spring:
  profiles:
    active: postgresql
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        cache:
          use_query_cache: false
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
