version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fkdlqmfjfl
      MYSQL_DATABASE: library
      MYSQL_USER: library
      MYSQL_PASSWORD: fkdlqmfjfl

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: fkdlqmfjfl
      POSTGRES_DB: library
      POSTGRES_USER: library
